apiVersion: batch/v1
kind: CronJob 
metadata:
  name: bontebok-job
spec:
  schedule: "@weekly"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: bontebok-bot
            image: charlesdalton/bontebok-bot:latest
            env:
            - name: BONTEBOK_TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bontebok-telegram-token
                  key: BONTEBOK_TELEGRAM_TOKEN
